#!/bin/bash
#mysql> select CONCAT('ln -s generic.mysql.mirror.php ', table_name, '.php')
#    -> from tables
#    -> where table_schema in ('core_op', 'core_trans', 'trans_archive')
#    -> AND table_type = 'BASE TABLE';
ln -s generic.mysql.mirror.php AdSaleDates.php
ln -s generic.mysql.mirror.php PurchaseOrder.php
ln -s generic.mysql.mirror.php PurchaseOrderItems.php
ln -s generic.mysql.mirror.php UpdateLog.php
ln -s generic.mysql.mirror.php Users.php
ln -s generic.mysql.mirror.php batchBarcodes.php
ln -s generic.mysql.mirror.php batchCutPaste.php
ln -s generic.mysql.mirror.php batchList.php
ln -s generic.mysql.mirror.php batchMergeTable.php
ln -s generic.mysql.mirror.php batchType.php
ln -s generic.mysql.mirror.php batches.php
ln -s generic.mysql.mirror.php batchowner.php
ln -s generic.mysql.mirror.php cronBackup.php
ln -s generic.mysql.mirror.php custAvailablePrefs.php
ln -s generic.mysql.mirror.php custPreferences.php
ln -s generic.mysql.mirror.php custReceiptMessage.php
ln -s generic.mysql.mirror.php custdata.php
ln -s generic.mysql.mirror.php custdataBackup.php
ln -s generic.mysql.mirror.php customReceipt.php
ln -s generic.mysql.mirror.php customReports.php
ln -s generic.mysql.mirror.php dateRestrict.php
ln -s generic.mysql.mirror.php departments.php
ln -s generic.mysql.mirror.php deptMargin.php
ln -s generic.mysql.mirror.php deptSalesCodes.php
ln -s generic.mysql.mirror.php disableCoupon.php
ln -s generic.mysql.mirror.php emailLog.php
ln -s generic.mysql.mirror.php employees.php
ln -s generic.mysql.mirror.php houseCouponItems.php
ln -s generic.mysql.mirror.php houseCoupons.php
ln -s generic.mysql.mirror.php houseVirtualCoupons.php
ln -s generic.mysql.mirror.php likeCodes.php
ln -s generic.mysql.mirror.php memContact.php
ln -s generic.mysql.mirror.php memContactPrefs.php
ln -s generic.mysql.mirror.php memDates.php
ln -s generic.mysql.mirror.php memberCards.php
ln -s generic.mysql.mirror.php memberNotes.php
ln -s generic.mysql.mirror.php memdefaults.php
ln -s generic.mysql.mirror.php meminfo.php
ln -s generic.mysql.mirror.php memtype.php
ln -s generic.mysql.mirror.php originCountry.php
ln -s generic.mysql.mirror.php originCustomRegion.php
ln -s generic.mysql.mirror.php originStateProv.php
ln -s generic.mysql.mirror.php origins.php
ln -s generic.mysql.mirror.php prodDepartmentHistory.php
ln -s generic.mysql.mirror.php prodExtra.php
ln -s generic.mysql.mirror.php prodFlags.php
ln -s generic.mysql.mirror.php prodPhysicalLocation.php
ln -s generic.mysql.mirror.php prodPriceHistory.php
ln -s generic.mysql.mirror.php prodUpdate.php
ln -s generic.mysql.mirror.php prodUpdateArchive.php
ln -s generic.mysql.mirror.php productBackup.php
ln -s generic.mysql.mirror.php productUser.php
ln -s generic.mysql.mirror.php products.php
ln -s generic.mysql.mirror.php products_3Oct2012.php
ln -s generic.mysql.mirror.php products_WEFC_Toronto.php
ln -s generic.mysql.mirror.php reasoncodes.php
ln -s generic.mysql.mirror.php scaleItems.php
ln -s generic.mysql.mirror.php shelftags.php
ln -s generic.mysql.mirror.php subdepts.php
ln -s generic.mysql.mirror.php superDeptNames.php
ln -s generic.mysql.mirror.php superdepts.php
ln -s generic.mysql.mirror.php suspension_history.php
ln -s generic.mysql.mirror.php suspensions.php
ln -s generic.mysql.mirror.php taxrates.php
ln -s generic.mysql.mirror.php tenders.php
ln -s generic.mysql.mirror.php unfi.php
ln -s generic.mysql.mirror.php unfiCategories.php
ln -s generic.mysql.mirror.php unfi_order.php
ln -s generic.mysql.mirror.php upcLike.php
ln -s generic.mysql.mirror.php userGroupPrivs.php
ln -s generic.mysql.mirror.php userGroups.php
ln -s generic.mysql.mirror.php userKnownPrivs.php
ln -s generic.mysql.mirror.php userPrivs.php
ln -s generic.mysql.mirror.php userSessions.php
ln -s generic.mysql.mirror.php vendorContact.php
ln -s generic.mysql.mirror.php vendorDepartments.php
ln -s generic.mysql.mirror.php vendorItems.php
ln -s generic.mysql.mirror.php vendorLoadScripts.php
ln -s generic.mysql.mirror.php vendorSKUtoPLU.php
ln -s generic.mysql.mirror.php vendorSRPs.php
ln -s generic.mysql.mirror.php vendors.php
ln -s generic.mysql.mirror.php AR_EOM_Summary.php
ln -s generic.mysql.mirror.php CashPerformDay_cache.php
ln -s generic.mysql.mirror.php CompleteSpecialOrder.php
ln -s generic.mysql.mirror.php InvAdjustments.php
ln -s generic.mysql.mirror.php InvCache.php
ln -s generic.mysql.mirror.php InvDelivery.php
ln -s generic.mysql.mirror.php InvDeliveryArchive.php
ln -s generic.mysql.mirror.php InvDeliveryLM.php
ln -s generic.mysql.mirror.php InvSalesArchive.php
ln -s generic.mysql.mirror.php PendingSpecialOrder.php
ln -s generic.mysql.mirror.php SpecialOrderContact.php
ln -s generic.mysql.mirror.php SpecialOrderDeptMap.php
ln -s generic.mysql.mirror.php SpecialOrderHistory.php
ln -s generic.mysql.mirror.php SpecialOrderID.php
ln -s generic.mysql.mirror.php SpecialOrderNotes.php
ln -s generic.mysql.mirror.php SpecialOrderStatus.php
ln -s generic.mysql.mirror.php alog.php
ln -s generic.mysql.mirror.php ar_history.php
ln -s generic.mysql.mirror.php ar_history_backup.php
ln -s generic.mysql.mirror.php ar_history_sum.php
ln -s generic.mysql.mirror.php dlog_15.php
ln -s generic.mysql.mirror.php dtransactions.php
ln -s generic.mysql.mirror.php dtranstoday.php
ln -s generic.mysql.mirror.php efsnetRequest.php
ln -s generic.mysql.mirror.php efsnetRequestMod.php
ln -s generic.mysql.mirror.php efsnetResponse.php
ln -s generic.mysql.mirror.php efsnetTokens.php
ln -s generic.mysql.mirror.php lane_config.php
ln -s generic.mysql.mirror.php stockpurchases.php
ln -s generic.mysql.mirror.php suspended.php
ln -s generic.mysql.mirror.php trans_backup_201211.php
ln -s generic.mysql.mirror.php transarchive.php
ln -s generic.mysql.mirror.php valutecRequest.php
ln -s generic.mysql.mirror.php valutecRequestMod.php
ln -s generic.mysql.mirror.php valutecResponse.php
ln -s generic.mysql.mirror.php voidTransHistory.php
ln -s generic.mysql.mirror.php reportDataCache.php
ln -s generic.mysql.mirror.php sumDeptSalesByDay.php
ln -s generic.mysql.mirror.php sumDiscountsByDay.php
ln -s generic.mysql.mirror.php sumFlaggedSalesByDay.php
ln -s generic.mysql.mirror.php sumMemSalesByDay.php
ln -s generic.mysql.mirror.php sumMemTypeSalesByDay.php
ln -s generic.mysql.mirror.php sumRingSalesByDay.php
ln -s generic.mysql.mirror.php sumTendersByDay.php
ln -s generic.mysql.mirror.php sumUpcSalesByDay.php
ln -s generic.mysql.mirror.php transArchive00.php
ln -s generic.mysql.mirror.php transArchive201210.php
ln -s generic.mysql.mirror.php transArchive201211.php
ln -s generic.mysql.mirror.php transArchive201212.php
ln -s generic.mysql.mirror.php transArchive201301.php
ln -s generic.mysql.mirror.php transArchive201302.php
ln -s generic.mysql.mirror.php transArchive201303.php
ln -s generic.mysql.mirror.php transArchive201304.php
ln -s generic.mysql.mirror.php transArchive201305.php
ln -s generic.mysql.mirror.php transArchive201306.php
ln -s generic.mysql.mirror.php transArchive201307.php
ln -s generic.mysql.mirror.php transArchive201308.php
ln -s generic.mysql.mirror.php transArchive201309.php
ln -s generic.mysql.mirror.php transArchive201310.php
ln -s generic.mysql.mirror.php transArchive201311.php
ln -s generic.mysql.mirror.php transArchive201312.php

echo "Done"
exit 0
